// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using likeButtonApi.Data;

namespace Article.api.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20201203170111_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("likeButtonApi.Data.Like", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("qtdlikes")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("like");
                });
#pragma warning restore 612, 618
        }
    }
}
